name: "Multi Event Pipeline Workflow"
on:
  push:
    branches:
      - main
      - master
 
jobs:
    on-push: # job name
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master push"
              run: echo "Running on master push!"
